quadrantChart
    title Reach and engagement of calculators
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 Python Snake Game: [0.3, 0.6]
    quadrant-2 Python Calculator: [0.45, 0.23]
    quadrant-3 Python Math Library: [0.57, 0.69]
    quadrant-4 Python Graphing Calculator: [0.78, 0.34]
    quadrant-1 Python Scientific Calculator: [0.4, 0.34]
    quadrant-2 Python Matrix Calculator: [0.35, 0.78]
    quadrant-3 Python Financial Calculator: [0.5, 0.6]
    "Our Target Product": [0.6, 0.7]
